services:
  - type: web
    name: tab-content-manager
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: DB_HOST
        value: db4free.net
      - key: DB_USER
        value: your_user
      - key: DB_PASSWORD
        value: your_pass
      - key: DB_NAME
        value: your_db
